const data = [
    {
        id: "0",
        name: '1 Bed in Sobha Creek Vistas, MBR City (2811)',
        href: '#',
        price: 'AED 1,050,000',
        description: 'Get the full lineup of our Basic Tees. Have a fresh shirt all week, and an extra for laundry day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/176/images/2512/1400px_main_96Pqw19gPC39yOptbd67GrNYI9X7yHOSD6al9ljP.jpeg',
        imageAlt: 'Eight shirts arranged on table in black, olive, grey, blue, white, red, mustard, and green.',
    },
    {
        id: "1",
        name: '1 Bed in Sky Gardens, DIFC (1310)',
        href: '#',
        price: 'AED 1,649,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/175/images/2488/1000px_main_9g2DpYWR0D114M0jf0EGNZ7guhki4OOlPjombmOu.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
    {
        id: "2",
        name: '1 Bed in Executive Residences, Dubai Hills (111)',
        href: '#',
        price: 'AED 1,441,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/177/images/2514/1510px_main_HyWV0iATCO9i0QODfYPj8VZJngDih1Y4MZOljENK.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
    {
        id: "3",
        name: '2 Bed Townhouse in Springs 7, The Springs & Meadows',
        href: '#',
        price: 'AED 2,924,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/174/images/2481/1920px_main_Xfqiy0vkRgpBuKXsD9KdvlKAf2p5fHq2VAgq44Z0.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
    {
        id: "4",
        name: 'Studio in Botanica Tower, Dubai Marina (3406)',
        href: '#',
        price: 'AED 1,035,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/179/images/2546/2400px_main_btHM6GX5okVRqZZVtGsdLVfnYbk0Gl8zEUba5M6n.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
    {
        id: "5",
        name: '1 Bed in West Avenue, Dubai Marina (206)',
        href: '#',
        price: 'AED 1,035,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/180/images/2565/1000px_main_wTQk1XZ0Jqc4vhW5ZkjPAFFGJP0OVz8QwC1kQypF.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
    {
        id: "6",
        name: 'Studio in Sobha Hartland Greens, MBR City (61005)',
        href: '#',
        price: 'AED 884,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/183/images/2605/2400px_main_cBfGzDp0JOTc1j9XrPcTgVN2MTnIwPPUNVqMagxs.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
    {
        id: "7",
        name: '1 Bed in Park Heights II, Dubai Hills (809)',
        href: '#',
        price: 'AED 1,356,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/183/images/2606/2340px_main_5C0BaaTwfRlnJj30uaF1RzrukW49NQNZCeyijY6y.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
    {
        id: "8",
        name: 'Studio in Sobha Hartland Greens, MBR City (6107)',
        href: '#',
        price: 'AED 877,000',
        description: 'Look like a visionary CEO and wear the same black t-shirt every day.',
        options: 'Dubai',
        imageSrc: 'https://stake-dev-env.s3.eu-west-1.amazonaws.com/properties/178/images/2540/1280px_main_GkdBL6AueDt4Kqu1cGKOKNeCRSrnHuiWbbvBhbN6.jpeg',
        imageAlt: 'Front of plain black t-shirt.',
    },
]

export async function GET() {
    return Response.json(data)
}